### ISSUE TITLE
FLDC17 Design Feedback

### ISSUE THREAD

**Issue by mherchel** [florida-drupalcamp/fldc-d7#9]
Hey Everyone,

After a discussion with @ThatGuyCND earlier, I want to get some feedback on the FLDC17 design (here: http://stage.fldrupal.camp/). Feel free to be super-critical.

A bit of history: The old theme hasn't changed since 2014. In my opinion, it looked excellent then, but now is looking a bit dated.

With that in mind, I figured it was time for a refresh. My goals were:
- Update the design to something more modern looking
- Give a bit of momentum to the conference (we had the most attendees back in 14)
- Visually convey that we're going to have some changes this year.
- Launch early.
- Be slightly different than [Drupalcamp Chattanooga](http://drupalcampchattanooga.com/) :D

With that in mind, I made these changes to the theme (all of these are on the front page)
- Moved the Drupal diver off of the front page simply because it looked awkward (imo). Note Drupal.org did a similar thing (depreciating the druplicon on the homepage).
- Added the video of the conference (stolen from @mrconnerton's vlogging video). 
- Added a large CTA superimposed on top of the video
- Slightly changed the layout of the featured speakers. Made it less "bubbly"
### Thoughts on all of this?
- Do you like the new homepage better than the old?
- Is the diver logo needed? If so, why?
- What's your thoughts on the video? Keep in mind we have [limited footage available](https://www.youtube.com/watch?v=3asmTqcoVp4).

cc @ultimike @JCL324 @jeppy64 and everyone else. Please comment!

**Comment by JCL324** [comment]
I think the home page without the diver is way too stark.  He's the mascot/branding/logo that we worked so hard on a few years ago! Please please, bring him back.

**Comment by jeppy64** [comment]
I'd go with mindset and opportunity for creative direction.

1: If the mindset is to launch in D7 to get out of the gate early to get web and SEO traction for ticket sales, I'd leave the old theme and back end up as is.  (yep I know... not very sexy). I don't see a reason to devote time and energy to something we will decommission anyway. (this is my least favorite option)

2: If the mindset is to launch in D8 then I see opportunity to gut the whole front end and go with a totally new creative direction. (this would be my choice). Personally, I like clean, sharp text (OpenSans for example) and minimal layout (I call it elbow room). White space isn't a bad thing. I hate to admit it, don't shoot me, but WordPress has this mastered. Featured Speakers and Session content should be what we push heavy. Even a robust news feed could change the whole feel of everything.

The diver: I remember when Dustin did that graphic. It was a huge hit! Question really is... do the organizers love it that much to continue with it as a branding standard. That should answer that question. Personally, do I think a camp needs a brand or logo standard? Nahhhh.. not really. Is it cute? Yep. But... if it is loved that much, the diver should become part of the logo itself and never change. I don't think it needs to take up valuable real estate in place of pushing Speaker and Session content.

Just my 2 cents

p.s. On the video: It is kinda cool, but on that first page hit, the pre-loading reminds me of the old "Flash - Loading, Please Wait" deal. Personally, I'd rather see more camp related content as a call to action section.  Maybe a call for Sponsorship, Volunteers, News (SEO valuable stuff)

**Comment by ultimike** [comment]
I like the Drupal Diver. It's part of our identity/brand.

I'd like to see it on the site, so allow me to offer a possible solution. Why not add a small version of the full-color diver to the top of each page - to the right or left of "FLORIDA DRUPALCAMP 2017". It doesn't have to be big to reinforce our brand.

If that's not enough, perhaps also add it to the footer - next to the FAQ link (at least in desktop mode).

Thoughts?

thanks,  
-mike

**Comment by mherchel** [comment]
Yeah, throwing the full-colored diver on top of the video looks weird. I thought about turning it into white outlines, but I wasn't able to do it properly because my sketch/illustrator skills aren't that up to par. 

I do want to use the new theme though, mainly because 1) it's done, and 2) The last theme has been used for the past 3 years. 

I'll add it to the Florida Drupalcamp text, and into the footer. I'll also still try to get the diver transformed into white lines (where it looks good), so I can experiment with throwing it in a more prominent position.

At that point, we can at least get the site launched.
